
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Danielyt
 */
public class SearchVideosPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchVideosPanel
     */
    private Object[] foundVideos;
    private Object videoFeed;
    private String searchTerm = "";
    public SearchVideosPanel() {
        initComponents();
        videoResultsTable.setAutoCreateRowSorter(true);
    }

    public void setFoundVideos(Object[] videos){
        foundVideos = new Object[videos.length];
        for(int i = 0; i < videos.length; i++)
            foundVideos[i] = videos[i];
        fillVideoResultsTable();        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void fillVideoResultsTable(){
        DefaultTableModel model = (DefaultTableModel) videoResultsTable.getModel();
        model.setRowCount(0);
        if(foundVideos != null) {
            Object[] videoRow;
            for (int i = 0; i < foundVideos.length; i++){
                videoRow = YouTubeActions.getVideoEntryInfo(foundVideos[i]);
                if (videoRow != null)
                    model.addRow(videoRow);
            }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTermTextField = new javax.swing.JTextField();
        searchVideosButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        videoResultsTable = new javax.swing.JTable();
        previousPageButton = new javax.swing.JButton();
        nextPageButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1100, 500));

        searchTermTextField.setColumns(25);
        searchTermTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTermTextFieldKeyPressed(evt);
            }
        });
        add(searchTermTextField);

        searchVideosButton.setText("Search");
        searchVideosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchVideosButtonActionPerformed(evt);
            }
        });
        add(searchVideosButton);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1100, 430));
        jScrollPane1.setRequestFocusEnabled(false);

        videoResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Uploaded by", "Video ID", "Description", "Keywords", "Latitude", "Longitude", "Average rating", "View count", "Duration"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Float.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(videoResultsTable);

        add(jScrollPane1);

        previousPageButton.setText("Previous");
        previousPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousPageButtonActionPerformed(evt);
            }
        });
        add(previousPageButton);

        nextPageButton.setText("Next");
        nextPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPageButtonActionPerformed(evt);
            }
        });
        add(nextPageButton);
    }// </editor-fold>//GEN-END:initComponents

    private void doSearch(){
        searchTerm = searchTermTextField.getText();
        if (!searchTerm.equals("")) {
            videoFeed = YouTubeActions.searchVideos(searchTerm);
            setFoundVideos(YouTubeActions.getVideoFeed(videoFeed));
        }
    }
    private void searchVideosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchVideosButtonActionPerformed
        // TODO add your handling code here:
        doSearch();
    }//GEN-LAST:event_searchVideosButtonActionPerformed

    private void previousPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousPageButtonActionPerformed
        // TODO add your handling code here:
        if (!searchTerm.equals("")) {
            videoFeed = YouTubeActions.getPreviousFeed(videoFeed);
            setFoundVideos(YouTubeActions.getVideoFeed(videoFeed));
        }
    }//GEN-LAST:event_previousPageButtonActionPerformed

    private void nextPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPageButtonActionPerformed
        // TODO add your handling code here:
        if (!searchTerm.equals("")) {
            videoFeed = YouTubeActions.getNextFeed(videoFeed);
            setFoundVideos(YouTubeActions.getVideoFeed(videoFeed));
        }
    }//GEN-LAST:event_nextPageButtonActionPerformed

    private void searchTermTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTermTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            doSearch();
        }
    }//GEN-LAST:event_searchTermTextFieldKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextPageButton;
    private javax.swing.JButton previousPageButton;
    private javax.swing.JTextField searchTermTextField;
    private javax.swing.JButton searchVideosButton;
    private javax.swing.JTable videoResultsTable;
    // End of variables declaration//GEN-END:variables
}
