
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Danielyt
 */
public class UserUploadsPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserUploadsPanel
     */
    private Object[] uploadedVideos;
    public UserUploadsPanel() {
        initComponents();
        userUploadsTable.setAutoCreateRowSorter(true);
    }

    public void setUploadedVideos(Object[] obj){
        uploadedVideos = new Object[obj.length];
        for(int i = 0; i < obj.length; i++)
            uploadedVideos[i] = obj[i];
        fillUserUploadsTable();
    }
    
    public void fillUserUploadsTable(){
        DefaultTableModel model = (DefaultTableModel) userUploadsTable.getModel();
        model.setRowCount(0);
        if(uploadedVideos != null) {
            Object[] videoRow;
            for (int i = 0; i < uploadedVideos.length; i++){
                videoRow = YouTubeActions.getVideoEntryInfo(uploadedVideos[i]);
                if (videoRow != null)
                    model.addRow(videoRow);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userUploadsTable = new javax.swing.JTable();
        refreshUploadsButton = new javax.swing.JButton();
        removeUploadedVideosButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1100, 500));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1100, 458));

        userUploadsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Uploaded by", "Video ID", "Description", "Keywords", "Latitude", "Longitude", "Average rating", "View count", "Duration"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Float.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userUploadsTable);

        add(jScrollPane1);

        refreshUploadsButton.setText("Refresh");
        refreshUploadsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshUploadsButtonActionPerformed(evt);
            }
        });
        add(refreshUploadsButton);

        removeUploadedVideosButton.setText("Remove");
        removeUploadedVideosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeUploadedVideosButtonActionPerformed(evt);
            }
        });
        add(removeUploadedVideosButton);
    }// </editor-fold>//GEN-END:initComponents

    private void refreshUploadsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshUploadsButtonActionPerformed
        // TODO add your handling code here:
        setUploadedVideos(YouTubeActions.getUploadedVideos());
    }//GEN-LAST:event_refreshUploadsButtonActionPerformed

    private void removeUploadedVideosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeUploadedVideosButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) userUploadsTable.getModel();
        int[] rows = userUploadsTable.getSelectedRows();
        for (int i = 0; i < rows.length; i++) {
            rows[i] = userUploadsTable.convertRowIndexToModel(rows[i]);
        }
        Arrays.sort(rows);
        for(int i=rows.length - 1; i >=0; i--){
            System.out.println(userUploadsTable.getValueAt(rows[i], 2));
            YouTubeActions.deleteVideoEntry(uploadedVideos, (String)userUploadsTable.getValueAt(rows[i], 2));
            model.removeRow(rows[i]);            
        }
        setUploadedVideos(YouTubeActions.getUploadedVideos());
    }//GEN-LAST:event_removeUploadedVideosButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshUploadsButton;
    private javax.swing.JButton removeUploadedVideosButton;
    private javax.swing.JTable userUploadsTable;
    // End of variables declaration//GEN-END:variables
}
